server:
  port: 7004
  servlet:
    context-path: /
spring:
  application:
    name: springboot-dubbo-customert
dubbo:
  application:
    id: springboot-dubbo-customert
    name: springboot-dubbo-customert
    qos-enable: true
    qos-port: 22224
    qos-accept-foreign-ip: true
  registry:
    id: customer-registry
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20888
    name: dubbo
    id: dubbo
  consumer:
    timeout: 60000
    filter: traceConsumerFilter
  trace:
    enabled: true
    connectTimeout: 1000
    readTimeout: 1000
    zipkinUrl: http://127.0.0.1:9411
  version: 1.0.0
  scan:
    base-packages: com.example.customert.dubboService